name: Run Manual workflow for PR TEST
on:
  workflow_dispatch:
    inputs:
      test_dir:
        type: choice
        description: What suite to run
        required: false
        options:
        - run_test
jobs:
  Run_Selected_Tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: GET Pull Request Information
        run: |
          export GIT_PR_NUMBER="1234" >> $GITHUB_ENV
          echo GIT_REPOSITORY_NAME="${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo GIT_ORG_NAME="${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "BRANCH_NAME_ENV=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
#          export GIT_PR_NUMBER="${{ github.event.number }}" >> $GITHUB_ENV

      - name: Execute Sanity Cases
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TC_SANITY_EXECUTION: ${{ secrets.TC_SANITY_EXECUTION }}
          JIRA_CONDITION: ${{ secrets.JIRA_CONDITION }}
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          JIRA_GITHUB_TOOL: ${{ secrets.JIRA_GITHUB_TOOL }}
          FAIL_STATUS_TRANSITION: ${{ secrets.FAIL_STATUS_TRANSITION }}
          PASS_STATUS_TRANSITION: ${{ secrets.PASS_STATUS_TRANSITION }}
          PREFIX_TICKET_VALUE: ${{ secrets.PREFIX_TICKET_VALUE }}
#          GIT_REPOSITORY_NAME: ${{ github.event.repository.name }}
#          GIT_ORG_NAME: ${{ github.repository_owner }}
        if: TC_SANITY_EXECUTION == 'True'
        run: |
          echo "Sanity cases"
          echo $GIT_REPOSITORY_NAME
          echo $GIT_ORG_NAME
          echo $BRANCH_NAME_ENV
#          pytest /test_cases/api/*/sanity_cases
