name: Run Manual workflow for PR TEST
on:
  workflow_dispatch:
    inputs:
      test_dir:
        type: choice
        description: What suite to run
        required: false
        options:
        - run_test
jobs:
  Run_Selected_Tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: GET Pull Request Information
        run: |
          export GIT_PR_NUMBER="1234" 
          export GIT_REPOSITORY_NAME="${{ github.event.repository.name }}"
          export GIT_ORG_NAME="${{ github.repository_owner }}"
#          export GIT_PR_NUMBER="${{ github.event.number }}"

      - name: Run Sanity cases
        run: |
          echo ${{ secrets.TC_SANITY_EXECUTION }} | sed 's/./&/g'
          echo ${{ secrets.AUTH_TOKEN }} | sed 's/./&/g'
#          TC_SANITY_EXECUTION:"${{ secrets.TC_SANITY_EXECUTION }}"
#          AUTH_TOKEN:"${{ secrets.AUTH_TOKEN }}"
#          echo ${{ TC_SANITY_EXECUTION }}
#          echo ${{ AUTH_TOKEN }}
#          export TC_SANITY_EXECUTION=TC_SANITY_EXECUTION
#          export AUTH_TOKEN=$AUTH_TOKEN

